ALTER TABLE users ADD COLUMN status TEXT NOT NULL DEFAULT 'online';
ALTER TABLE users ADD COLUMN last_seen INTEGER;
ALTER TABLE users ADD COLUMN share_last_seen INTEGER NOT NULL DEFAULT 1;
ALTER TABLE users ADD COLUMN share_typing INTEGER NOT NULL DEFAULT 1;
